##GlacierVotes Main Configuration
## Github : https://github.com/Khuirul-Huda/GlacierVotes
# Made with ❤️ by @khuirul_huda
# not affiliated with minecraftpocket-servers.com

##Config Version (DONT TOUCH!)
configver: 2

##API KEY IS REQUIRED !
##API KEY from minecraftpocket-servers.com
apikey: "null"

#Send message to players?(no-Vote)
notice: true
#Notice Message
nvmessage: "Heyy, please support this server with your votes"

# Commands run when someone votes your server
# %player% = Player
commands:
- give %player% diamond_sword 1
- give %player% diamond_axe 1

##Enable Debug Mode? (Show More Information)
debug: false


#### DISCORD WEBHOOK SECTION ▁▁▁▁▁▁▁▁▁▁

##Enable discord webhook? "null" if you don't want this feature. 
# 
# ⚠️ WARNING ⚠️
#
# Beware that this doesn't escape the JSON strings!
#  i highly recommend to use json escaper online because this part uses JSON!
#
# Taken from the site https://www.freeformatter.com/json-escape.html
#
# Backspace is replaced with \b
# Form feed is replaced with \f
# Newline is replaced with \n
# Carriage return is replaced with \r
# Tab is replaced with \t
# Double quote is replaced with \"
# Backslash is replaced with \\
#
# ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ #
# Discord Webhook URL
webhook: "null"
avatarurl: "https://"
servername: "RenderyCrafty" #Your server name
username: "Vote Logger"
thumbnail: "https://files.yourserver.net" #thumbnail for embed
description: "%player% Thank you for your votes!" # %player% as Player
footer: "Vote https://vote.yourserver.net"

