name: GlacierVotes
main: me.khuirulhuda.glaciervotes.Main
version: 1.0-SNAPSHOT
website: https://khuirul-huda.github.io/GlacierVotes
description: Simple plugin to receive votes from minecraft pe sites
author: Khuirul-Huda
load: POSTWORLD

commands:
    gvreload:
        description: Reload the plugin (op only)
        usage: /gvreload
       
        